## CMPINF 2100 Week 04
### Pandas DataFrame index deep drive
let's focus heavily on .index attribute of a DataFrame

## Import Modules

In [1]:
import numpy as np
import pandas as pd

## Example DataFrame
We will use the same baseball example DF from the prevous one
Create DF from a dictionary

In [2]:
baseball_dict = {'City': ['Pittsburgh', 'Cincinnati', 'Chicago', 'St. Louis', 'Milwaukee'],
                'Team': ['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
                 'Division': 5 * ['Central'],
                 'League': 5 * ['NL']}

In [3]:
baseball_dict

{'City': ['Pittsburgh', 'Cincinnati', 'Chicago', 'St. Louis', 'Milwaukee'],
 'Team': ['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
 'Division': ['Central', 'Central', 'Central', 'Central', 'Central'],
 'League': ['NL', 'NL', 'NL', 'NL', 'NL']}

In [4]:
baseball_df = pd.DataFrame(baseball_dict)

In [5]:
baseball_df

         City       Team Division League
0  Pittsburgh    Pirates  Central     NL
1  Cincinnati       Reds  Central     NL
2     Chicago       Cubs  Central     NL
3   St. Louis  Cardinals  Central     NL
4   Milwaukee    Brewers  Central     NL

In [8]:
baseball_df.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
baseball_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   City      5 non-null      object
 1   Team      5 non-null      object
 2   Division  5 non-null      object
 3   League    5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes

but we can change the index attribute

Pandas allow the '.index' attribute be anything
Let's see

In [11]:
baseball_df.index = [31.5, 27.5, 22.5, 0, 7.5]

In [12]:
baseball_df.index

Index([31.5, 27.5, 22.5, 0.0, 7.5], dtype='float64')

In [13]:
baseball_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 31.5 to 7.5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   City      5 non-null      object
 1   Team      5 non-null      object
 2   Division  5 non-null      object
 3   League    5 non-null      object
dtypes: object(4)
memory usage: 200.0+ bytes

In [14]:
baseball_df

            City       Team Division League
31.5  Pittsburgh    Pirates  Central     NL
27.5  Cincinnati       Reds  Central     NL
22.5     Chicago       Cubs  Central     NL
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL

How can we find a single row or SELECT a single row from the DataFrame?

In [15]:
baseball_df[ 0 ]

KeyError: 0

In [16]:
baseball_df[ 0.0 ]

KeyError: 0.0

Pandas is COLUMN or variable or field centric!!!

In [17]:
baseball_df

            City       Team Division League
31.5  Pittsburgh    Pirates  Central     NL
27.5  Cincinnati       Reds  Central     NL
22.5     Chicago       Cubs  Central     NL
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL

When we type the [] to access SOMETHING in a Pandas DataFrame... we need to provide the COLUMN NAME

In [19]:
baseball_df['City']

31.5    Pittsburgh
27.5    Cincinnati
22.5       Chicago
0.0      St. Louis
7.5      Milwaukee
Name: City, dtype: object

In [20]:
baseball_df['Team']

31.5      Pirates
27.5         Reds
22.5         Cubs
0.0     Cardinals
7.5       Brewers
Name: Team, dtype: object

In [21]:
baseball_df.columns

Index(['City', 'Team', 'Division', 'League'], dtype='object')

but how does this help us with the ROWS!!
the .index attribute is associated with the rows

In [22]:
baseball_df.index

Index([31.5, 27.5, 22.5, 0.0, 7.5], dtype='float64')

Absolutely — here’s a clear and compact summary of **`.loc[]`** and **`.iloc[]`** in **pandas**, the two primary ways to access rows and columns in a DataFrame 👇

---

## 🧠 pandas `.loc[]` vs `.iloc[]` — Summary

| Feature                    | `.loc[]`                                         | `.iloc[]`                                  |
| -------------------------- | ------------------------------------------------ | ------------------------------------------ |
| **Purpose**                | Label-based indexing                             | Integer (position)-based indexing          |
| **Syntax**                 | `df.loc[row_labels, column_labels]`              | `df.iloc[row_positions, column_positions]` |
| **Indexing Type**          | Uses **row/column labels** (names, index values) | Uses **integer positions** (0-based)       |
| **Inclusive or Exclusive** | **Inclusive** of both start and end labels       | **Exclusive** of end (like Python slicing) |
| **Examples**               | `df.loc['A']` → row with index `'A'`             | `df.iloc[0]` → first row                   |
| **Slice Example**          | `df.loc['A':'C']` → includes both A and C        | `df.iloc[0:3]` → includes 0,1,2 (not 3)    |
| **Select Multiple**        | `df.loc[['A', 'C'], ['col1', 'col3']]`           | `df.iloc[[0, 2], [1, 3]]`                  |
| **Boolean Masking**        | ✅ Supported                                      | ✅ Supported                                |
| **Assignment**             | ✅ Used to modify data                            | ✅ Used to modify data                      |

---

## 🔍 Examples

Assume:

```python
import pandas as pd

df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40],
    'city': ['NY', 'LA', 'Chicago', 'Houston']
}, index=['a', 'b', 'c', 'd'])
```

### 1️⃣ Using `.loc[]` — Label-based

```python
df.loc['b']                     # Row with index label 'b'
df.loc['b', 'city']             # Single value (Bob's city)
df.loc['a':'c', ['name', 'age']]  # Rows a–c, columns name & age
df.loc[df['age'] > 30]          # Filtered by condition
```

### 2️⃣ Using `.iloc[]` — Position-based

```python
df.iloc[1]                      # Second row (Bob)
df.iloc[1, 2]                   # Row 1, column 2 → 'LA'
df.iloc[0:3, 0:2]               # First 3 rows, first 2 columns
df.iloc[[0, 2], [1, 2]]         # Rows 0,2 and columns 1,2
```

---

## ⚡ Key Tips

* `.loc[]` → Think **“by label”** (index/column names)
* `.iloc[]` → Think **“by location”** (numerical positions)
* Both can be used to **get** or **set** data:

  ```python
  df.loc['a', 'age'] = 26
  df.iloc[0, 1] = 26
  ```

---

### 🧩 Imagine this DataFrame

```python
import pandas as pd

df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'age': [25, 30, 35, 40],
    'city': ['NY', 'LA', 'Chicago', 'Houston']
}, index=['a', 'b', 'c', 'd'])
```

The DataFrame looks like this:

| index | name    | age | city    |
| :---- | :------ | --: | :------ |
| a     | Alice   |  25 | NY      |
| b     | Bob     |  30 | LA      |
| c     | Charlie |  35 | Chicago |
| d     | David   |  40 | Houston |

---

### 🔍 Indexing Map (Side-by-side view)

```
     LABEL-BASED (for .loc[])       POSITION-BASED (for .iloc[])
     ─────────────────────────      ────────────────────────────
Row labels:   a   b   c   d          Row positions:  0   1   2   3
Column names: name  age  city        Column positions: 0   1   2
```

---

### 🎯 Examples Compared Side-by-Side

| Operation                 | Using `.loc[]` (by label)          | Using `.iloc[]` (by position)      | Result         |
| ------------------------- | ---------------------------------- | ---------------------------------- | -------------- |
| Select 1st row            | `df.loc['a']`                      | `df.iloc[0]`                       | Alice’s row    |
| Select 2nd column         | `df.loc[:, 'age']`                 | `df.iloc[:, 1]`                    | ages only      |
| Row b, Column city        | `df.loc['b', 'city']`              | `df.iloc[1, 2]`                    | `'LA'`         |
| Rows a–c, cols name & age | `df.loc['a':'c', ['name', 'age']]` | `df.iloc[0:3, 0:2]`                | Subset         |
| Multiple rows (b, d)      | `df.loc[['b', 'd']]`               | `df.iloc[[1, 3]]`                  | Bob, David     |
| Filter condition          | `df.loc[df['age'] > 30]`           | `df.iloc[(df['age'] > 30).values]` | Charlie, David |

---

### 🧠 Quick Rules to Remember

| Concept                             | `.loc[]`                      | `.iloc[]` |
| ----------------------------------- | ----------------------------- | --------- |
| Uses labels (index names)           | ✅                             | ❌         |
| Uses positions (row/column numbers) | ❌                             | ✅         |
| End label in slice included         | ✅ Yes                         | ❌ No      |
| Works with boolean masks            | ✅                             | ✅         |
| Works with numeric range like `0:3` | ❌ (unless labels are numbers) | ✅         |

---

### 🧩 Visual Example in Text

```
DataFrame Grid (row, column):

           name   age   city
index
a (0) →   Alice   25    NY
b (1) →   Bob     30    LA
c (2) →   Charlie 35    Chicago
d (3) →   David   40    Houston

.loc['b', 'city']   → LA   (by label)
.iloc[1, 2]         → LA   (by position)
.loc['a':'c', 'name'] → Alice, Bob, Charlie
.iloc[0:3, 0]         → Alice, Bob, Charlie
```

---

In [24]:
baseball_df

            City       Team Division League
31.5  Pittsburgh    Pirates  Central     NL
27.5  Cincinnati       Reds  Central     NL
22.5     Chicago       Cubs  Central     NL
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL

In [25]:
baseball_df.loc[0.0] # location KEY

City        St. Louis
Team        Cardinals
Division      Central
League             NL
Name: 0.0, dtype: object

In [26]:
baseball_df.loc[31.5]

City        Pittsburgh
Team           Pirates
Division       Central
League              NL
Name: 31.5, dtype: object

In [29]:
baseball_df.iloc[0] # first row

City        Pittsburgh
Team           Pirates
Division       Central
League              NL
Name: 31.5, dtype: object

In [30]:
baseball_df.iloc[-1] # last row

City        Milwaukee
Team          Brewers
Division      Central
League             NL
Name: 7.5, dtype: object

The `.loc[]` attribute selects ROWS based on `.index` LOCATION KEY!!!
The `.iloc[]` attribute selects ROWS based on `.index` INTEGER POSITION!!!
# Resetting Index
Prefer it to be a regular column if it is storing MEANINGful Values

In [32]:
baseball_df

            City       Team Division League
31.5  Pittsburgh    Pirates  Central     NL
27.5  Cincinnati       Reds  Central     NL
22.5     Chicago       Cubs  Central     NL
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL

In [33]:
baseball_df.sort_index() # sort menthod

            City       Team Division League
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL
22.5     Chicago       Cubs  Central     NL
27.5  Cincinnati       Reds  Central     NL
31.5  Pittsburgh    Pirates  Central     NL

In [34]:
baseball_df

            City       Team Division League
31.5  Pittsburgh    Pirates  Central     NL
27.5  Cincinnati       Reds  Central     NL
22.5     Chicago       Cubs  Central     NL
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL

In [35]:
baseball_df.sort_index( inplace=True)

In [36]:
baseball_df

            City       Team Division League
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL
22.5     Chicago       Cubs  Central     NL
27.5  Cincinnati       Reds  Central     NL
31.5  Pittsburgh    Pirates  Central     NL

We can PULL OUT the .index attribute inot a REGULAR column using the .reset_index() method!

In [37]:
baseball_df.reset_index()

   index        City       Team Division League
0    0.0   St. Louis  Cardinals  Central     NL
1    7.5   Milwaukee    Brewers  Central     NL
2   22.5     Chicago       Cubs  Central     NL
3   27.5  Cincinnati       Reds  Central     NL
4   31.5  Pittsburgh    Pirates  Central     NL

In [38]:
baseball_df.reset_index().info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   index     5 non-null      float64
 1   City      5 non-null      object
 2   Team      5 non-null      object
 3   Division  5 non-null      object
 4   League    5 non-null      object
dtypes: float64(1), object(4)
memory usage: 328.0+ bytes

If you don't want to keep the value within the .index attribute when you reset you can DROP them!

In [40]:
baseball_df.reset_index(drop=True)

         City       Team Division League
0   St. Louis  Cardinals  Central     NL
1   Milwaukee    Brewers  Central     NL
2     Chicago       Cubs  Central     NL
3  Cincinnati       Reds  Central     NL
4  Pittsburgh    Pirates  Central     NL

We can rename the column using .rename() method!!! we need to use a DICTIONARY within the columns argument of the .rename() method!!!
The KEY is the original column name and the VALUE is the NEW or desired column name!

In [42]:
baseball_df.reset_index().rename(columns={'index':'games_back'})

   games_back        City       Team Division League
0         0.0   St. Louis  Cardinals  Central     NL
1         7.5   Milwaukee    Brewers  Central     NL
2        22.5     Chicago       Cubs  Central     NL
3        27.5  Cincinnati       Reds  Central     NL
4        31.5  Pittsburgh    Pirates  Central     NL

In [43]:
baseball_df

            City       Team Division League
0.0    St. Louis  Cardinals  Central     NL
7.5    Milwaukee    Brewers  Central     NL
22.5     Chicago       Cubs  Central     NL
27.5  Cincinnati       Reds  Central     NL
31.5  Pittsburgh    Pirates  Central     NL

sometimes we want to place each step in a PIPELINE or WORKFLOW of actions on a separate line
This makes the code easier to read especially when there are MANY MANY actions in the WORKFLOW

In [45]:
baseball_df_b = baseball_df.\
reset_index().\
rename(columns={'index':'games_back'})

In [46]:
baseball_df_b

   games_back        City       Team Division League
0         0.0   St. Louis  Cardinals  Central     NL
1         7.5   Milwaukee    Brewers  Central     NL
2        22.5     Chicago       Cubs  Central     NL
3        27.5  Cincinnati       Reds  Central     NL
4        31.5  Pittsburgh    Pirates  Central     NL

## Index upon creation
The `.index` attribute can be defined when the DataFrame is created

In [49]:
baseball_df_c = pd.DataFrame(data = baseball_dict,
                            index = [31.5, 27.5, 22.5, 0, 7.5],
                            columns = ['League', 'Division', 'City', 'Team'])

In [50]:
baseball_df_c

     League Division        City       Team
31.5     NL  Central  Pittsburgh    Pirates
27.5     NL  Central  Cincinnati       Reds
22.5     NL  Central     Chicago       Cubs
0.0      NL  Central   St. Louis  Cardinals
7.5      NL  Central   Milwaukee    Brewers