### CMPINF 2100 WEEK 04
Columns and Rows in the Pandas DataFrames
We have seen how to create the DataFrame. We have worked with the .index attribute. We now need to practice selecting columns and rows within the DF

In [1]:
import numpy as np
import pandas as pd

## Create example Data
We will make the Dictionary about baseball and then convert that Dictionary to a DF

In [2]:
baseball_dict = {'City': ['Pittsburgh', 'Cincinati', 'Chicago', 'St. Louis', 'Milwaukee'],
                'Team':['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
                'Division': 5 * ['Central'],
                'League': 5 * ['NL']}

In [3]:
baseball_dict

{'City': ['Pittsburgh', 'Cincinati', 'Chicago', 'St. Louis', 'Milwaukee'],
 'Team': ['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
 'Division': ['Central', 'Central', 'Central', 'Central', 'Central'],
 'League': ['NL', 'NL', 'NL', 'NL', 'NL']}

In [4]:
baseball_df = pd.DataFrame( baseball_dict,
                          columns=['League', 'Division', 'City', 'Team'])

In [5]:
baseball_df

  League Division        City       Team
0     NL  Central  Pittsburgh    Pirates
1     NL  Central   Cincinati       Reds
2     NL  Central     Chicago       Cubs
3     NL  Central   St. Louis  Cardinals
4     NL  Central   Milwaukee    Brewers

In [6]:
baseball_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   League    5 non-null      object
 1   Division  5 non-null      object
 2   City      5 non-null      object
 3   Team      5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes

## Columns
### Selecting columns

In [7]:
baseball_df['Team']

0      Pirates
1         Reds
2         Cubs
3    Cardinals
4      Brewers
Name: Team, dtype: object

In [8]:
baseball_df['Division']

0    Central
1    Central
2    Central
3    Central
4    Central
Name: Division, dtype: object

In [9]:
type( baseball_df['Division'] )

pandas.core.series.Series

In [10]:
baseball_df['Division'].index

RangeIndex(start=0, stop=5, step=1)

There is another way to access or select a single column and retrurn it as a Series
The previous way the BRACKET notation
But this other way is known as the DOT NOTATION

In [11]:
baseball_df.City

0    Pittsburgh
1     Cincinati
2       Chicago
3     St. Louis
4     Milwaukee
Name: City, dtype: object

Still another approach is to use the FORMAL .loc[] attribute for selecting the COLUMN

In [12]:
baseball_df.loc[:, 'Team']

0      Pirates
1         Reds
2         Cubs
3    Cardinals
4      Brewers
Name: Team, dtype: object

In [13]:
baseball_df.loc[:, 'Division' ]

0    Central
1    Central
2    Central
3    Central
4    Central
Name: Division, dtype: object

In [14]:
baseball_df.loc[:, 'City']

0    Pittsburgh
1     Cincinati
2       Chicago
3     St. Louis
4     Milwaukee
Name: City, dtype: object

In [15]:
type(baseball_df.loc[:, 'City'])

pandas.core.series.Series

In [16]:
baseball_df.iloc[:, 0]

0    NL
1    NL
2    NL
3    NL
4    NL
Name: League, dtype: object

In [17]:
baseball_df.iloc[:, -1]

0      Pirates
1         Reds
2         Cubs
3    Cardinals
4      Brewers
Name: Team, dtype: object

In [18]:
baseball_df.loc[:, 'Team']

0      Pirates
1         Reds
2         Cubs
3    Cardinals
4      Brewers
Name: Team, dtype: object

In [19]:
baseball_df.columns

Index(['League', 'Division', 'City', 'Team'], dtype='object')

However, be very careful...with how you ENTER or TYPE the column names!

In [20]:
baseball_df.loc[:,'Team']

0      Pirates
1         Reds
2         Cubs
3    Cardinals
4      Brewers
Name: Team, dtype: object

In [21]:
baseball_df.loc[:, ['Team'] ]

        Team
0    Pirates
1       Reds
2       Cubs
3  Cardinals
4    Brewers

In [22]:
baseball_df.loc[:, ['Team', 'City'] ]

        Team        City
0    Pirates  Pittsburgh
1       Reds   Cincinati
2       Cubs     Chicago
3  Cardinals   St. Louis
4    Brewers   Milwaukee

we need the base Python List to SELECT multiple columns from the Dataframe!!!

### Adding and Deleting columns
Adding columns simliar to how we added new KEY/Values pairs to Dictionaries
Let's start with the VSLUE that will be added

In [23]:
baseball_df

  League Division        City       Team
0     NL  Central  Pittsburgh    Pirates
1     NL  Central   Cincinati       Reds
2     NL  Central     Chicago       Cubs
3     NL  Central   St. Louis  Cardinals
4     NL  Central   Milwaukee    Brewers

In [24]:
baseball_df['games_back'] = [31.5, 27.5, 22.5, 0, 7.5]

In [25]:
baseball_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   League      5 non-null      object
 1   Division    5 non-null      object
 2   City        5 non-null      object
 3   Team        5 non-null      object
 4   games_back  5 non-null      float64
dtypes: float64(1), object(4)
memory usage: 328.0+ bytes

In [26]:
baseball_df

  League Division        City       Team  games_back
0     NL  Central  Pittsburgh    Pirates        31.5
1     NL  Central   Cincinati       Reds        27.5
2     NL  Central     Chicago       Cubs        22.5
3     NL  Central   St. Louis  Cardinals         0.0
4     NL  Central   Milwaukee    Brewers         7.5

In [27]:
baseball_df.sort_values(['games_back'], inplace=True)

In [28]:
baseball_df

  League Division        City       Team  games_back
3     NL  Central   St. Louis  Cardinals         0.0
4     NL  Central   Milwaukee    Brewers         7.5
2     NL  Central     Chicago       Cubs        22.5
1     NL  Central   Cincinati       Reds        27.5
0     NL  Central  Pittsburgh    Pirates        31.5

Let's add anotehr clumn which contains the number of WINS per team
This new column will be assigned to Pandas Series rather than a list

In [29]:
baseball_df['wins'] = pd.Series([87,79,64,59,55], index=baseball_df.index)

In [30]:
baseball_df

  League Division        City       Team  games_back  wins
3     NL  Central   St. Louis  Cardinals         0.0    87
4     NL  Central   Milwaukee    Brewers         7.5    79
2     NL  Central     Chicago       Cubs        22.5    64
1     NL  Central   Cincinati       Reds        27.5    59
0     NL  Central  Pittsburgh    Pirates        31.5    55

In [31]:
baseball_df.wins

3    87
4    79
2    64
1    59
0    55
Name: wins, dtype: int64

In [32]:
baseball_df['losses'] = pd.Series([63, 70, 85, 90, 94], index=baseball_df.index)

In [33]:
baseball_df

  League Division        City       Team  games_back  wins  losses
3     NL  Central   St. Louis  Cardinals         0.0    87      63
4     NL  Central   Milwaukee    Brewers         7.5    79      70
2     NL  Central     Chicago       Cubs        22.5    64      85
1     NL  Central   Cincinati       Reds        27.5    59      90
0     NL  Central  Pittsburgh    Pirates        31.5    55      94

But what if we want to add a SCALAR or CONSTANT value to the DataFrame?
For e.g. I want a column named 'season' to store the year the data came from
At first we might think we need to do the following to add the column:

In [34]:
pd.Series([2022,2022,2022,2022,2022], index=baseball_df.index)

3    2022
4    2022
2    2022
1    2022
0    2022
dtype: int64

In [36]:
pd.Series(5*[2022], index=baseball_df.index)

3    2022
4    2022
2    2022
1    2022
0    2022
dtype: int64

But we don't need to do these just add the following and Pandas will replicate the constant value donw all the rows of the new column

In [37]:
baseball_df['season']=2022

In [38]:
baseball_df

  League Division        City       Team  games_back  wins  losses  season
3     NL  Central   St. Louis  Cardinals         0.0    87      63    2022
4     NL  Central   Milwaukee    Brewers         7.5    79      70    2022
2     NL  Central     Chicago       Cubs        22.5    64      85    2022
1     NL  Central   Cincinati       Reds        27.5    59      90    2022
0     NL  Central  Pittsburgh    Pirates        31.5    55      94    2022

## Deleting or Dropping columns
We can remove columns through the .drop() method

In [41]:
baseball_df.drop(columns=['season'])

  League Division        City       Team  games_back  wins  losses
3     NL  Central   St. Louis  Cardinals         0.0    87      63
4     NL  Central   Milwaukee    Brewers         7.5    79      70
2     NL  Central     Chicago       Cubs        22.5    64      85
1     NL  Central   Cincinati       Reds        27.5    59      90
0     NL  Central  Pittsburgh    Pirates        31.5    55      94

In [42]:
baseball_df.drop(columns=['wins', 'losses', 'season'])

  League Division        City       Team  games_back
3     NL  Central   St. Louis  Cardinals         0.0
4     NL  Central   Milwaukee    Brewers         7.5
2     NL  Central     Chicago       Cubs        22.5
1     NL  Central   Cincinati       Reds        27.5
0     NL  Central  Pittsburgh    Pirates        31.5

In [43]:
baseball_df

  League Division        City       Team  games_back  wins  losses  season
3     NL  Central   St. Louis  Cardinals         0.0    87      63    2022
4     NL  Central   Milwaukee    Brewers         7.5    79      70    2022
2     NL  Central     Chicago       Cubs        22.5    64      85    2022
1     NL  Central   Cincinati       Reds        27.5    59      90    2022
0     NL  Central  Pittsburgh    Pirates        31.5    55      94    2022

we sould need to set the implace argument to True to RETAIN or Keep the resulting DataFrame that has FEWER columns!

## Setting Rows
We know how to use the .loc[] and .iloc[] attributes to select rows based on the .index attribute

In [45]:
baseball_df.loc[3] #everything assoicated with '3'

League               NL
Division        Central
City          St. Louis
Team          Cardinals
games_back          0.0
wins                 87
losses               63
season             2022
Name: 3, dtype: object

In [47]:
baseball_df.iloc[3] #everthing associated with index 3\

League               NL
Division        Central
City          Cincinati
Team               Reds
games_back         27.5
wins                 59
losses               90
season             2022
Name: 1, dtype: object

Conditionally subset the rows

In [49]:
baseball_df.wins > 65

3     True
4     True
2    False
1    False
0    False
Name: wins, dtype: bool

In [51]:
baseball_df.loc[ baseball_df.wins > 65]

  League Division       City       Team  games_back  wins  losses  season
3     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
4     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

In [54]:
baseball_df.loc[ baseball_df['wins'] > 65]

  League Division       City       Team  games_back  wins  losses  season
3     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
4     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

In [56]:
baseball_df.loc[ baseball_df.wins > 65, :] # official way to say return all the columns that matches the  condition

  League Division       City       Team  games_back  wins  losses  season
3     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
4     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

we can select a subset of the columns by providing a LIST of column names!

In [58]:
baseball_df.loc[ baseball_df.wins > 65, ['Team', 'wins', 'losses']]

        Team  wins  losses
3  Cardinals    87      63
4    Brewers    79      70

we can also FILTER by strings. For e.g, lets find the row where Team =='Brewers'

In [60]:
baseball_df.loc[ baseball_df.Team == 'Brewers', :]

  League Division       City     Team  games_back  wins  losses  season
4     NL  Central  Milwaukee  Brewers         7.5    79      70    2022

In [61]:
baseball_df.loc[ baseball_df.Team == 'Pirates', :]

  League Division        City     Team  games_back  wins  losses  season
0     NL  Central  Pittsburgh  Pirates        31.5    55      94    2022

If you want to match or FILTER based on MULTIPLE conditions you need to use () to separate each condition.
For e.g. let's find brewers or cardinals

In [63]:
baseball_df.loc[ (baseball_df.Team == 'Brewers') | (baseball_df.Team == 'Cardinals'), :]

  League Division       City       Team  games_back  wins  losses  season
3     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
4     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

We can also have an AND operation
I want to find all rows where Team is equal to Cardinals AND the wins is greater than 65

In [64]:
baseball_df.loc[ (baseball_df.Team == 'Cardinals') & (baseball_df.wins > 65), :]

  League Division       City       Team  games_back  wins  losses  season
3     NL  Central  St. Louis  Cardinals         0.0    87      63    2022

## Summary
We have seen how to select COLUMNS using BRACKET and DOT notations.
We have seen how to select MULTIPLE columns.
We have seen how to select ROWS based on '.index' attribute via '.loc[]' and '.iloc[]'.
We have seen how to select ROWWS based on conditions (Filtering rows)
We also saw how to add and remore (drop) columns