## CMPINF 2100 Week 05
### Combine DataFrames: JOIN or MERGE

In [1]:
import numpy as np
import pandas as pd

## Read Data
Let's read in the 3 CSV files from the previous recording.

In [2]:
dfA = pd.read_csv('Example_A.csv')

In [3]:
dfB = pd.read_csv('Example_B.csv')

In [4]:
dfC = pd.read_csv('Example_C.csv')

Examining the 'dfA' and dfB DataFrames

In [5]:
dfA

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [6]:
dfB

    E    G
0  aa  100
1  bb  200
2  dd  400

JOINING OR MERGING data COMBINE DataFrames NOT based on the row or column POSITION...but based on the VALUES of variables (columns)!!!!

## Join or Merge
The 'pd.merge()' function JOINS TWO DataFrames.
We need to specify the TWO DataFrames AND we need to specify the column (or columns) that the two are JOINED ON!!!!
The JOINING variable is referred to as the ***KEY***!!!!!

In [7]:
pd.merge(dfA, dfB, on='E')

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

   A   B     C    D   E   F    G
0  a   0  -100  Jan  aa  10  100
1  b   1  -200  Feb  aa  20  100
2  c   2  -300  Mar  aa  10  100
3  d   3  -400  Apr  bb  20  200
4  e   4  -500  May  bb  10  200
5  f   5  -600  Jun  bb  20  200
6  j   9 -1000  Oct  dd  20  400
7  k  10 -1100  Nov  dd  10  400
8  l  11 -1200  Dec  dd  20  400

In [9]:
dfA.shape

(12, 6)

what happened to the missing rows
The answer has to do with the unique values of the KEY between LEFT and RIGHT data sets!!!

In [10]:
dfA

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

The E == 'cc' value is NOT present in the JOINED data set!!!
This is because in addition ot specifying the KEY that we JOIN ON...we also must specify **HOW** the LEFT and RIGHT dataframes are JOINED!!!
By defalt Pandas uses **INNER** joins!!!
The INNER JOIN keeps all values that are consistent for the KEY between the two data sets!!!
or...the KEY VALUES must be shared between the TWO!!!

In [12]:
pd.merge(dfA, dfB, on='E', how='inner')

   A   B     C    D   E   F    G
0  a   0  -100  Jan  aa  10  100
1  b   1  -200  Feb  aa  20  100
2  c   2  -300  Mar  aa  10  100
3  d   3  -400  Apr  bb  20  200
4  e   4  -500  May  bb  10  200
5  f   5  -600  Jun  bb  20  200
6  j   9 -1000  Oct  dd  20  400
7  k  10 -1100  Nov  dd  10  400
8  l  11 -1200  Dec  dd  20  400

Other types of JOINS
The LEFT JOIN keeps all KEY values present in the LEFT data set

In [15]:
pd.merge(dfA, dfB, on='E', how='left')

    A   B     C    D   E   F      G
0   a   0  -100  Jan  aa  10  100.0
1   b   1  -200  Feb  aa  20  100.0
2   c   2  -300  Mar  aa  10  100.0
3   d   3  -400  Apr  bb  20  200.0
4   e   4  -500  May  bb  10  200.0
5   f   5  -600  Jun  bb  20  200.0
6   g   6  -700  Jul  cc  10    NaN
7   h   7  -800  Aug  cc  20    NaN
8   i   8  -900  Sep  cc  10    NaN
9   j   9 -1000  Oct  dd  20  400.0
10  k  10 -1100  Nov  dd  10  400.0
11  l  11 -1200  Dec  dd  20  400.0

NaN = Not a number

In [16]:
pd.merge(dfA, dfB, on='E', how='right')

   A   B     C    D   E   F    G
0  a   0  -100  Jan  aa  10  100
1  b   1  -200  Feb  aa  20  100
2  c   2  -300  Mar  aa  10  100
3  d   3  -400  Apr  bb  20  200
4  e   4  -500  May  bb  10  200
5  f   5  -600  Jun  bb  20  200
6  j   9 -1000  Oct  dd  20  400
7  k  10 -1100  Nov  dd  10  400
8  l  11 -1200  Dec  dd  20  400

For this result RIGHT JOIN and INNER JOIN produce the same results
The LEFT JOIN generated the MISSING vallues
It all depends on the data sets 
Let's see what happens if we use a RIGHT JOIN between dfA and dfC

In [17]:
dfA

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [18]:
dfC

    F    H
0  10  AAA
1  20  BBB
2  30  CCC
3  40  DDD

In [19]:
 pd.merge(dfA, dfC, on='F', how='right')

      A     B       C    D    E   F    H
0     a   0.0  -100.0  Jan   aa  10  AAA
1     c   2.0  -300.0  Mar   aa  10  AAA
2     e   4.0  -500.0  May   bb  10  AAA
3     g   6.0  -700.0  Jul   cc  10  AAA
4     i   8.0  -900.0  Sep   cc  10  AAA
5     k  10.0 -1100.0  Nov   dd  10  AAA
6     b   1.0  -200.0  Feb   aa  20  BBB
7     d   3.0  -400.0  Apr   bb  20  BBB
8     f   5.0  -600.0  Jun   bb  20  BBB
9     h   7.0  -800.0  Aug   cc  20  BBB
10    j   9.0 -1000.0  Oct   dd  20  BBB
11    l  11.0 -1200.0  Dec   dd  20  BBB
12  NaN   NaN     NaN  NaN  NaN  30  CCC
13  NaN   NaN     NaN  NaN  NaN  40  DDD

In [20]:
 pd.merge(dfA, dfC, on='F', how='left')

    A   B     C    D   E   F    H
0   a   0  -100  Jan  aa  10  AAA
1   b   1  -200  Feb  aa  20  BBB
2   c   2  -300  Mar  aa  10  AAA
3   d   3  -400  Apr  bb  20  BBB
4   e   4  -500  May  bb  10  AAA
5   f   5  -600  Jun  bb  20  BBB
6   g   6  -700  Jul  cc  10  AAA
7   h   7  -800  Aug  cc  20  BBB
8   i   8  -900  Sep  cc  10  AAA
9   j   9 -1000  Oct  dd  20  BBB
10  k  10 -1100  Nov  dd  10  AAA
11  l  11 -1200  Dec  dd  20  BBB

In [21]:
 pd.merge(dfA, dfC, on='F', how='inner')

    A   B     C    D   E   F    H
0   a   0  -100  Jan  aa  10  AAA
1   c   2  -300  Mar  aa  10  AAA
2   e   4  -500  May  bb  10  AAA
3   g   6  -700  Jul  cc  10  AAA
4   i   8  -900  Sep  cc  10  AAA
5   k  10 -1100  Nov  dd  10  AAA
6   b   1  -200  Feb  aa  20  BBB
7   d   3  -400  Apr  bb  20  BBB
8   f   5  -600  Jun  bb  20  BBB
9   h   7  -800  Aug  cc  20  BBB
10  j   9 -1000  Oct  dd  20  BBB
11  l  11 -1200  Dec  dd  20  BBB

MISSING values can be "generated" by JOINS!!!
We are bringing together COLUMNS from one data set into another data set
IF we do not have an exact assciation between the columns, the the missing occur.
May to the larger data set as left and smaller as right 
You can aslo use just .merge()

In [23]:
dfA.merge(dfC, on='F', how='inner')

    A   B     C    D   E   F    H
0   a   0  -100  Jan  aa  10  AAA
1   c   2  -300  Mar  aa  10  AAA
2   e   4  -500  May  bb  10  AAA
3   g   6  -700  Jul  cc  10  AAA
4   i   8  -900  Sep  cc  10  AAA
5   k  10 -1100  Nov  dd  10  AAA
6   b   1  -200  Feb  aa  20  BBB
7   d   3  -400  Apr  bb  20  BBB
8   f   5  -600  Jun  bb  20  BBB
9   h   7  -800  Aug  cc  20  BBB
10  j   9 -1000  Oct  dd  20  BBB
11  l  11 -1200  Dec  dd  20  BBB

we can merge multiple datasetns in one line of code

In [24]:
pd.merge(dfA, dfB, on='E', how='left').merge(dfC, on='F', how='right')

      A     B       C    D    E   F      G    H
0     a   0.0  -100.0  Jan   aa  10  100.0  AAA
1     c   2.0  -300.0  Mar   aa  10  100.0  AAA
2     e   4.0  -500.0  May   bb  10  200.0  AAA
3     g   6.0  -700.0  Jul   cc  10    NaN  AAA
4     i   8.0  -900.0  Sep   cc  10    NaN  AAA
5     k  10.0 -1100.0  Nov   dd  10  400.0  AAA
6     b   1.0  -200.0  Feb   aa  20  100.0  BBB
7     d   3.0  -400.0  Apr   bb  20  200.0  BBB
8     f   5.0  -600.0  Jun   bb  20  200.0  BBB
9     h   7.0  -800.0  Aug   cc  20    NaN  BBB
10    j   9.0 -1000.0  Oct   dd  20  400.0  BBB
11    l  11.0 -1200.0  Dec   dd  20  400.0  BBB
12  NaN   NaN     NaN  NaN  NaN  30    NaN  CCC
13  NaN   NaN     NaN  NaN  NaN  40    NaN  DDD

The INNER JOIN used by Pandas by default tries to minimize MISSINGS.
Let's assign the results of this JOIN to a new variable

In [25]:
df = pd.merge(dfA, dfB, on='E', how='left').merge(dfC, on='F', how='right')

In [26]:
df

      A     B       C    D    E   F      G    H
0     a   0.0  -100.0  Jan   aa  10  100.0  AAA
1     c   2.0  -300.0  Mar   aa  10  100.0  AAA
2     e   4.0  -500.0  May   bb  10  200.0  AAA
3     g   6.0  -700.0  Jul   cc  10    NaN  AAA
4     i   8.0  -900.0  Sep   cc  10    NaN  AAA
5     k  10.0 -1100.0  Nov   dd  10  400.0  AAA
6     b   1.0  -200.0  Feb   aa  20  100.0  BBB
7     d   3.0  -400.0  Apr   bb  20  200.0  BBB
8     f   5.0  -600.0  Jun   bb  20  200.0  BBB
9     h   7.0  -800.0  Aug   cc  20    NaN  BBB
10    j   9.0 -1000.0  Oct   dd  20  400.0  BBB
11    l  11.0 -1200.0  Dec   dd  20  400.0  BBB
12  NaN   NaN     NaN  NaN  NaN  30    NaN  CCC
13  NaN   NaN     NaN  NaN  NaN  40    NaN  DDD

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       12 non-null     object
 1   B       12 non-null     float64
 2   C       12 non-null     float64
 3   D       12 non-null     object
 4   E       12 non-null     object
 5   F       14 non-null     int64
 6   G       9 non-null      float64
 7   H       14 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.0+ KB

In [28]:
df.describe()

               B            C          F           G
count  12.000000    12.000000  14.000000    9.000000
mean    5.500000  -650.000000  17.857143  233.333333
std     3.605551   360.555128   8.925824  132.287566
min     0.000000 -1200.000000  10.000000  100.000000
25%     2.750000  -925.000000  10.000000  100.000000
50%     5.500000  -650.000000  20.000000  200.000000
75%     8.250000  -375.000000  20.000000  400.000000
max    11.000000  -100.000000  40.000000  400.000000

### Write to files
we created a JOINED data set Let's save that JOINED data set to a CSV file

In [37]:
df.to_csv('joined_data.csv', index=False)

In [30]:
import os

In [38]:
os.listdir()

['Example_A.csv',
 'Example_B.csv',
 'Example_C.csv',
 'week_05_filter_pandas_with_strings.ipynb',
 'joined_data.csv',
 'Excel_Example_Data.xlsx',
 'week_05_combine_concat.ipynb',
 'week_05_read_data.ipynb',
 '.ipynb_checkpoints',
 'week_05_combine_joins_or_merge.ipynb']

Let's compare the datasets

In [39]:
df_again = pd.read_csv('joined_data.csv')

In [41]:
df_again

      A     B       C    D    E   F      G    H
0     a   0.0  -100.0  Jan   aa  10  100.0  AAA
1     c   2.0  -300.0  Mar   aa  10  100.0  AAA
2     e   4.0  -500.0  May   bb  10  200.0  AAA
3     g   6.0  -700.0  Jul   cc  10    NaN  AAA
4     i   8.0  -900.0  Sep   cc  10    NaN  AAA
5     k  10.0 -1100.0  Nov   dd  10  400.0  AAA
6     b   1.0  -200.0  Feb   aa  20  100.0  BBB
7     d   3.0  -400.0  Apr   bb  20  200.0  BBB
8     f   5.0  -600.0  Jun   bb  20  200.0  BBB
9     h   7.0  -800.0  Aug   cc  20    NaN  BBB
10    j   9.0 -1000.0  Oct   dd  20  400.0  BBB
11    l  11.0 -1200.0  Dec   dd  20  400.0  BBB
12  NaN   NaN     NaN  NaN  NaN  30    NaN  CCC
13  NaN   NaN     NaN  NaN  NaN  40    NaN  DDD

In [45]:
dfA.merge(dfC, on='F', how='right')

      A     B       C    D    E   F    H
0     a   0.0  -100.0  Jan   aa  10  AAA
1     c   2.0  -300.0  Mar   aa  10  AAA
2     e   4.0  -500.0  May   bb  10  AAA
3     g   6.0  -700.0  Jul   cc  10  AAA
4     i   8.0  -900.0  Sep   cc  10  AAA
5     k  10.0 -1100.0  Nov   dd  10  AAA
6     b   1.0  -200.0  Feb   aa  20  BBB
7     d   3.0  -400.0  Apr   bb  20  BBB
8     f   5.0  -600.0  Jun   bb  20  BBB
9     h   7.0  -800.0  Aug   cc  20  BBB
10    j   9.0 -1000.0  Oct   dd  20  BBB
11    l  11.0 -1200.0  Dec   dd  20  BBB
12  NaN   NaN     NaN  NaN  NaN  30  CCC
13  NaN   NaN     NaN  NaN  NaN  40  DDD