## CMPINF 2100 WEEK 05
### Read data into Pandas
## Import Modules

In [1]:
import numpy as np
import pandas as pd

In [2]:
import os

In [4]:
os.listdir()

['Example_A.csv',
 'Example_B.csv',
 'Example_C.csv',
 'week_05_filter_pandas_with_strings.ipynb',
 'Excel_Example_Data.xlsx',
 'week_05_read_data.ipynb',
 '.ipynb_checkpoints']

In [5]:
os.getcwd()

'/Users/jok208/Documents/ADDM/courses/CMPINF2100/publish/compinf2100_project/week_05'

## Read Excel file

In [6]:
pd.read_excel('Excel_Example_Data.xlsx')

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [8]:
df0 = pd.read_excel( 'Excel_Example_Data.xlsx')

In [10]:
%whos

Variable   Type         Data/Info
---------------------------------
df0        DataFrame        A   B     C    D   E <...> l  11 -1200  Dec  dd  20
np         module       <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
os         module       <module 'os' from '/opt/a<...>100/lib/python3.8/os.py'>
pd         module       <module 'pandas' from '/o<...>ages/pandas/__init__.py'>

In [12]:
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       12 non-null     object
 1   B       12 non-null     int64
 2   C       12 non-null     int64
 3   D       12 non-null     object
 4   E       12 non-null     object
 5   F       12 non-null     int64
dtypes: int64(3), object(3)
memory usage: 704.0+ bytes

We can force one of the column to be index attribute when the data are read

In [15]:
df0_b = pd.read_excel('Excel_Example_Data.xlsx', index_col=0)

In [16]:
df0_b

    B     C    D   E   F
A
a   0  -100  Jan  aa  10
b   1  -200  Feb  aa  20
c   2  -300  Mar  aa  10
d   3  -400  Apr  bb  20
e   4  -500  May  bb  10
f   5  -600  Jun  bb  20
g   6  -700  Jul  cc  10
h   7  -800  Aug  cc  20
i   8  -900  Sep  cc  10
j   9 -1000  Oct  dd  20
k  10 -1100  Nov  dd  10
l  11 -1200  Dec  dd  20

In [17]:
df0_b.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'], dtype='object', name='A')

In [18]:
df0_b.loc[ 'a']

B       0
C    -100
D     Jan
E      aa
F      10
Name: a, dtype: object

In [19]:
df0_b.loc[ 'c']

B       2
C    -300
D     Mar
E      aa
F      10
Name: c, dtype: object

In [21]:
df0_b.shape

(12, 5)

In [22]:
# By default NONE of the columns are trated as the .index and we can assing any colunmn using 
df0_b = pd.read_excel('Excel_Example_Data.xlsx', index_col=0) # changing the col=0 to any other column

### Headers or Column names
by default the pd.read_* family of functions assumes the top row is the Header row
the top row threfore does NOT contain VALUES! instead it is assumed the TOP ROW or HEADER contains the COLUMN NAMES

In [23]:
df0.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [25]:
df0

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

### Handling worksheet with no headers
when you know there is NO HEADER then the header argument must be set to None

In [26]:
df0_no_names = pd.read_excel( 'Excel_Example_Data.xlsx', sheet_name='no_headers', header=None)

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [27]:
df0_no_names

    0   1     2    3   4   5
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [28]:
df0_no_names_2 = pd.read_excel('Excel_Example_Data.xlsx',
                                sheet_name='no_headers',
                               header=None,
                               names=df0.columns)

In [29]:
df0_no_names_2

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [30]:
df0_no_names_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       12 non-null     object
 1   B       12 non-null     int64
 2   C       12 non-null     int64
 3   D       12 non-null     object
 4   E       12 non-null     object
 5   F       12 non-null     int64
dtypes: int64(3), object(3)
memory usage: 704.0+ bytes

 ### Read Other Sheets
Just specify the sheet_name argument appropriately

In [32]:
pd.read_excel('Excel_Example_Data.xlsx', sheet_name='ExB')

    E    G
0  aa  100
1  bb  200
2  dd  400

In [33]:
pd.read_excel('Excel_Example_Data.xlsx', sheet_name='ExC')

    F    H
0  10  AAA
1  20  BBB
2  30  CCC
3  40  DDD

 ### Read CSV
 CSV files have the extension '.csv'. Unlike Excel they contain a single spreadsheet

In [34]:
pd.read_csv('Example_A.csv')

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [36]:
pd.read_csv('Example_A.csv')

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [37]:
pd.read_csv('Example_A.csv', nrows=3)

   A  B    C    D   E   F
0  a  0 -100  Jan  aa  10
1  b  1 -200  Feb  aa  20
2  c  2 -300  Mar  aa  10

In [38]:
pd.read_csv('Example_A.csv', skiprows=2)

   b   1  -200  Feb  aa  20
0  c   2  -300  Mar  aa  10
1  d   3  -400  Apr  bb  20
2  e   4  -500  May  bb  10
3  f   5  -600  Jun  bb  20
4  g   6  -700  Jul  cc  10
5  h   7  -800  Aug  cc  20
6  i   8  -900  Sep  cc  10
7  j   9 -1000  Oct  dd  20
8  k  10 -1100  Nov  dd  10
9  l  11 -1200  Dec  dd  20

When you skip rows be very careful with the HEADER!!!

In [39]:
pd.read_csv( 'Example_A.csv', skiprows=2, header=None)

    0   1     2    3   4   5
0   b   1  -200  Feb  aa  20
1   c   2  -300  Mar  aa  10
2   d   3  -400  Apr  bb  20
3   e   4  -500  May  bb  10
4   f   5  -600  Jun  bb  20
5   g   6  -700  Jul  cc  10
6   h   7  -800  Aug  cc  20
7   i   8  -900  Sep  cc  10
8   j   9 -1000  Oct  dd  20
9   k  10 -1100  Nov  dd  10
10  l  11 -1200  Dec  dd  20

In [40]:
dfA = pd.read_csv( 'Example_A.csv')

In [41]:
dfB = pd.read_csv( 'Example_B.csv')

In [42]:
dfC = pd.read_csv( 'Example_C.csv')

In [44]:
dfA

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [45]:
dfB

    E    G
0  aa  100
1  bb  200
2  dd  400

In [46]:
dfC

    F    H
0  10  AAA
1  20  BBB
2  30  CCC
3  40  DDD

## Read or download from a website

TSV file - Tab separated Value

In [48]:
gap_url = 'https://raw.githubusercontent.com/chendaniely/pandas_for_everyone/master/data/gapminder.tsv'

In [49]:
type(gap_url)

str

To read in the data we provide the URL web address as a string instad of a file name on our computer
Because we are reading a TAB separated rather than a CSV we need to change the sep (separater) argument

In [50]:
gap_df = pd.read_csv(gap_url, sep='\t')

In [51]:
gap_df.shape

(1704, 6)

In [72]:
gap_df.loc[gap_df.country.isin(['United States', 'India'])]

            country continent  year  lifeExp         pop     gdpPercap
696           India      Asia  1952   37.373   372000000    546.565749
697           India      Asia  1957   40.249   409000000    590.061996
698           India      Asia  1962   43.605   454000000    658.347151
699           India      Asia  1967   47.193   506000000    700.770611
700           India      Asia  1972   50.651   567000000    724.032527
701           India      Asia  1977   54.208   634000000    813.337323
702           India      Asia  1982   56.596   708000000    855.723538
703           India      Asia  1987   58.553   788000000    976.512676
704           India      Asia  1992   60.223   872000000   1164.406809
705           India      Asia  1997   61.765   959000000   1458.817442
706           India      Asia  2002   62.879  1034172547   1746.769454
707           India      Asia  2007   64.698  1110396331   2452.210407
1608  United States  Americas  1952   68.440   157553000  13990.482080
1609  United States  Americas  1957   69.490   171984000  14847.127120
1610  United States  Americas  1962   70.210   186538000  16173.145860
1611  United States  Americas  1967   70.760   198712000  19530.365570
1612  United States  Americas  1972   71.340   209896000  21806.035940
1613  United States  Americas  1977   73.380   220239000  24072.632130
1614  United States  Americas  1982   74.650   232187835  25009.559140
1615  United States  Americas  1987   75.020   242803533  29884.350410
1616  United States  Americas  1992   76.090   256894189  32003.932240
1617  United States  Americas  1997   76.810   272911760  35767.433030
1618  United States  Americas  2002   77.310   287675526  39097.099550
1619  United States  Americas  2007   78.242   301139947  42951.653090

## Read or load data from Modules
We will use data from Modules throughout the ADDM program
We just need to make sure the module is imported

In [3]:
import seaborn as sns

In [4]:
titanic = sns.load_dataset('titanic')

In [77]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [5]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
10,1,3,female,4.00,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
22,1,3,female,15.00,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
39,1,3,female,14.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
125,1,3,male,12.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
165,1,3,male,9.00,0,2,20.5250,S,Third,child,False,NaN,Southampton,yes,False
172,1,3,female,1.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
184,1,3,female,4.00,0,2,22.0250,S,Third,child,False,NaN,Southampton,yes,False
233,1,3,female,5.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
381,1,3,female,1.00,0,2,15.7417,C,Third,child,False,NaN,Cherbourg,yes,False
448,1,3,female,5.00,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
479,1,3,female,2.00,0,1,12.2875,S,Third,child,False,NaN,Southampton,yes,False
489,1,3,male,9.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
691,1,3,female,4.00,0,1,13.4167,C,Third,child,False,NaN,Cherbourg,yes,False
751,1,3,male,6.00,0,1,12.4750,S,Third,child,False,E,Southampton,yes,False
777,1,3,female,5.00,0,0,12.4750,S,Third,child,False,NaN,Southampton,yes,True
780,1,3,female,13.00,0,0,7.2292,C,Third,child,False,NaN,Cherbourg,yes,True
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
830,1,3,female,15.00,1,0,14.4542,C,Third,child,False,NaN,Cherbourg,yes,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False
875,1,3,female,15.00,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True