## CMPINF 2100 Week 05
### Filter Pandas with strings
### Import Modules

In [1]:
import numpy as np
import pandas as pd

### Review of DataFrames
baseball related Dataframe

In [10]:
baseball_dict = {'City':['Pittsburgh', 'Cinicinati', 'Chicago', 'St. Louis', 'Milwaukee'] ,
                'Team':['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
                'Division': 5 * ['Central'],
                'League':5 * ['NL']}

In [11]:
baseball_dict

{'City': ['Pittsburgh', 'Cinicinati', 'Chicago', 'St. Louis', 'Milwaukee'],
 'Team': ['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
 'Division': ['Central', 'Central', 'Central', 'Central', 'Central'],
 'League': ['NL', 'NL', 'NL', 'NL', 'NL']}

In [12]:
 baseball_df = pd.DataFrame(baseball_dict, columns=['League', 'Division', 'City', 'Team'])

In [13]:
baseball_df

  League Division        City       Team
0     NL  Central  Pittsburgh    Pirates
1     NL  Central  Cinicinati       Reds
2     NL  Central     Chicago       Cubs
3     NL  Central   St. Louis  Cardinals
4     NL  Central   Milwaukee    Brewers

In [16]:
baseball_df['games_back'] = pd.Series([31.5, 27.5, 22.5, 0, 7.5], index=baseball_df.index)

In [17]:
baseball_df

  League Division        City       Team  games_back
0     NL  Central  Pittsburgh    Pirates        31.5
1     NL  Central  Cinicinati       Reds        27.5
2     NL  Central     Chicago       Cubs        22.5
3     NL  Central   St. Louis  Cardinals         0.0
4     NL  Central   Milwaukee    Brewers         7.5

sort by the games_back column ignore the index and modify  in place

In [18]:
baseball_df.sort_values(['games_back'], ignore_index=True, inplace=True)

In [19]:
baseball_df

  League Division        City       Team  games_back
0     NL  Central   St. Louis  Cardinals         0.0
1     NL  Central   Milwaukee    Brewers         7.5
2     NL  Central     Chicago       Cubs        22.5
3     NL  Central  Cinicinati       Reds        27.5
4     NL  Central  Pittsburgh    Pirates        31.5

Add two more columns that have values which change down the rows

In [20]:
baseball_df['wins'] = pd.Series([87, 79, 64, 59, 55], index=baseball_df.index)

In [21]:
baseball_df['losses'] = pd.Series([63, 70, 85, 90, 94], index=baseball_df.index)

In [22]:
baseball_df

  League Division        City       Team  games_back  wins  losses
0     NL  Central   St. Louis  Cardinals         0.0    87      63
1     NL  Central   Milwaukee    Brewers         7.5    79      70
2     NL  Central     Chicago       Cubs        22.5    64      85
3     NL  Central  Cinicinati       Reds        27.5    59      90
4     NL  Central  Pittsburgh    Pirates        31.5    55      94

In [23]:
baseball_df['season'] = 2022

In [24]:
baseball_df

  League Division        City       Team  games_back  wins  losses  season
0     NL  Central   St. Louis  Cardinals         0.0    87      63    2022
1     NL  Central   Milwaukee    Brewers         7.5    79      70    2022
2     NL  Central     Chicago       Cubs        22.5    64      85    2022
3     NL  Central  Cinicinati       Reds        27.5    59      90    2022
4     NL  Central  Pittsburgh    Pirates        31.5    55      94    2022

### Filter Rows
Filtering rows refers to SELECTING rows based on the CONDITIONAL TESTS

In [26]:
baseball_df.loc[ baseball_df.wins > 65, :]

  League Division       City       Team  games_back  wins  losses  season
0     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
1     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

In [28]:
baseball_df.loc[ baseball_df.Team == 'Pirates', :]

  League Division        City     Team  games_back  wins  losses  season
4     NL  Central  Pittsburgh  Pirates        31.5    55      94    2022

We also saw how to use the OR operator, '|', to find all row whwere the value equals A or B.
Or, the value is ONE of those presented.

In [30]:
baseball_df.loc[ (baseball_df.Team == 'Cardinals') | (baseball_df.Team == 'Brewers'), : ]

  League Division       City       Team  games_back  wins  losses  season
0     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
1     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

.isin() method to steramline the | operator

In [35]:
 baseball_df.loc[ baseball_df.Team.isin(['Cardinals', 'Brewers']), :]

  League Division       City       Team  games_back  wins  losses  season
0     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
1     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

In [36]:
 baseball_df.loc[ baseball_df.losses.isin([70, 90]), :]

  League Division        City     Team  games_back  wins  losses  season
1     NL  Central   Milwaukee  Brewers         7.5    79      70    2022
3     NL  Central  Cinicinati     Reds        27.5    59      90    2022

In [38]:
top_teams = baseball_df.loc[ baseball_df.games_back < 10, 'Team'].copy().tolist()

In [39]:
top_teams

['Cardinals', 'Brewers']

In [40]:
baseball_df.loc[ baseball_df.Team.isin( top_teams ), :]

  League Division       City       Team  games_back  wins  losses  season
0     NL  Central  St. Louis  Cardinals         0.0    87      63    2022
1     NL  Central  Milwaukee    Brewers         7.5    79      70    2022

## String Pattern Matching

In [42]:
baseball_df.loc[ baseball_df.City == 'Pittsburgh', :]

  League Division        City     Team  games_back  wins  losses  season
4     NL  Central  Pittsburgh  Pirates        31.5    55      94    2022

But what if I didn't feel like typing out the whole string or is there a typo - focus on the patern with .str.contains

In [44]:
baseball_df.loc[ baseball_df.City.str.contains('Pitt'), :]

  League Division        City     Team  games_back  wins  losses  season
4     NL  Central  Pittsburgh  Pirates        31.5    55      94    2022

In [45]:
baseball_df.loc[ baseball_df.City.str.contains('P'), :]

  League Division        City     Team  games_back  wins  losses  season
4     NL  Central  Pittsburgh  Pirates        31.5    55      94    2022

In [46]:
baseball_df.loc[ baseball_df.City.str.contains('C'), :]

  League Division        City  Team  games_back  wins  losses  season
2     NL  Central     Chicago  Cubs        22.5    64      85    2022
3     NL  Central  Cinicinati  Reds        27.5    59      90    2022

In [47]:
baseball_df.loc[ baseball_df.City.str.contains('\\.'), :]

  League Division       City       Team  games_back  wins  losses  season
0     NL  Central  St. Louis  Cardinals         0.0    87      63    2022

In [48]:
baseball_df.loc[ baseball_df.City.str.contains(' '), :]

  League Division       City       Team  games_back  wins  losses  season
0     NL  Central  St. Louis  Cardinals         0.0    87      63    2022

In [50]:
# baseball_df.loc[ baseball_df.City.str. # hit tab to see all the methods available

In [51]:
dir(baseball_df.City.str)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__frozen',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_data',
 '_doc_args',
 '_freeze',
 '_get_series_list',
 '_index',
 '_inferred_dtype',
 '_is_categorical',
 '_is_string',
 '_name',
 '_orig',
 '_parent',
 '_validate',
 '_wrap_result',
 'capitalize',
 'casefold',
 'cat',
 'center',
 'contains',
 'count',
 'decode',
 'encode',
 'endswith',
 'extract',
 'extractall',
 'find',
 'findall',
 'fullmatch',
 'get',
 'get_dummies',
 'index',
 'isalnum',
 'isalpha',
 'isdecimal',
 'isdigit',
 'islower',
 'isnumeric',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'len',
 'ljust',
 'lower',
 'lstrip',
 'match',
 'normalize',
 'pad',
 'partition',
 'removeprefix',
 'removesuffix',
 'repeat',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'slice',
 'slice_replace',
 'split',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'wrap',
 'zfill']