## CMPINF 2100 Week 05
### Summarize DataFrames for Exploratory Data Analysis (EDA)
## Import Modules

In [1]:
import numpy as np
import pandas as pd

## Read Data
Let's read in the JOINED data set we created previously

In [2]:
df = pd.read_csv('joined_data.csv')

In [3]:
df

      A     B       C    D    E   F      G    H
0     a   0.0  -100.0  Jan   aa  10  100.0  AAA
1     c   2.0  -300.0  Mar   aa  10  100.0  AAA
2     e   4.0  -500.0  May   bb  10  200.0  AAA
3     g   6.0  -700.0  Jul   cc  10    NaN  AAA
4     i   8.0  -900.0  Sep   cc  10    NaN  AAA
5     k  10.0 -1100.0  Nov   dd  10  400.0  AAA
6     b   1.0  -200.0  Feb   aa  20  100.0  BBB
7     d   3.0  -400.0  Apr   bb  20  200.0  BBB
8     f   5.0  -600.0  Jun   bb  20  200.0  BBB
9     h   7.0  -800.0  Aug   cc  20    NaN  BBB
10    j   9.0 -1000.0  Oct   dd  20  400.0  BBB
11    l  11.0 -1200.0  Dec   dd  20  400.0  BBB
12  NaN   NaN     NaN  NaN  NaN  30    NaN  CCC
13  NaN   NaN     NaN  NaN  NaN  40    NaN  DDD

## Summarize columns
We learned from the previous recording that summarizing columns in a DataFrame is accomplished just as we apply methods to summarize Pandas Series!

In [4]:
df.B.mean()

5.5

In [6]:
df['B'].mean()

5.5

In [8]:
df.F.mean()

17.857142857142858

How does Pandas deal with MISSING values?
The MISSINGS ARE DROPPED OR SKIPPED OR REMOVED before the summary fu ction is applied!

In [12]:
df.B.mean(skipna=True)

5.5

In [13]:
df.B.mean(skipna=False)

nan

MISSING values prevent the summary statistics from being calculated!!!
Many summary functions/methods DROP or SKIP MISSING values!

In [14]:
df.B.std()

3.605551275463989

In [15]:
df.B.var()

13.0

In [16]:
df.B.min()

0.0

In [18]:
df.B.max()

11.0

In [20]:
df.B.sem()

1.0408329997330663

In [22]:
df.mean(numeric_only=True)

B      5.500000
C   -650.000000
F     17.857143
G    233.333333
dtype: float64

In [23]:
df.sem(numeric_only=True)

B      1.040833
C    104.083300
F      2.385527
G     44.095855
dtype: float64

In [24]:
df.C.size

14

In [26]:
df.C.count()

12

The '.size' attribute is the number of elements in the column (series). While the '.count()' method returns the number of NON-MISSING entries

In [27]:
 df.C.std()/np.sqrt(df.C.count())

104.08329997330664

All of the previous methods have been used to summarize COLUMNS
However, like NumPy the methods do have the 'axis' argument...so we COULD apply them to individual ROWS and then summarize across columns rather than DOWN columns

In [33]:
df.mean(axis=1, numeric_only=True)

0       2.500000
1     -47.000000
2     -71.500000
3    -228.000000
4    -294.000000
5    -170.000000
6     -19.750000
7     -44.250000
8     -93.750000
9    -257.666667
10   -142.750000
11   -192.250000
12     30.000000
13     40.000000
dtype: float64

## Custom summary functions
We can define our own functions and APPLY them to the DataFrame
To demonstrate, let's define our own AVERAGE

In [34]:
def my_avg(x):
    """ assume x is a Pandas series
    and assume x is a numbers"""
    return x.sum()/x.count()

In [35]:
df.mean(numeric_only=True)

B      5.500000
C   -650.000000
F     17.857143
G    233.333333
dtype: float64

In [36]:
my_avg(df.F)

17.857142857142858

In [37]:
my_avg(df.C)

-650.0

 But to APPLY a custom function to the entire DatFrame...we need to use the .apply() method. So a METHOD is used to APPLY the function to the columns!

In [38]:
df.apply(my_avg)

TypeError: can only concatenate str (not "int") to str

We instead should only apply 'my_avg()' to NUMERIC columns!
A simple way to do that is to SELECT all NUMBERS in the DataFrame.
Pandas has a helper method '.select_dtypes()' that allows you to easily select all columns of a particular data type

In [39]:
df.select_dtypes('number').apply(my_avg)

B      5.500000
C   -650.000000
F     17.857143
G    233.333333
dtype: float64

In [40]:
df.mean(numeric_only=True)

B      5.500000
C   -650.000000
F     17.857143
G    233.333333
dtype: float64

### Methods for MISSING values
There are specilized and predefined methods dedicated too IDENTIFYING missing entries in a DataFrame

In [41]:
df

      A     B       C    D    E   F      G    H
0     a   0.0  -100.0  Jan   aa  10  100.0  AAA
1     c   2.0  -300.0  Mar   aa  10  100.0  AAA
2     e   4.0  -500.0  May   bb  10  200.0  AAA
3     g   6.0  -700.0  Jul   cc  10    NaN  AAA
4     i   8.0  -900.0  Sep   cc  10    NaN  AAA
5     k  10.0 -1100.0  Nov   dd  10  400.0  AAA
6     b   1.0  -200.0  Feb   aa  20  100.0  BBB
7     d   3.0  -400.0  Apr   bb  20  200.0  BBB
8     f   5.0  -600.0  Jun   bb  20  200.0  BBB
9     h   7.0  -800.0  Aug   cc  20    NaN  BBB
10    j   9.0 -1000.0  Oct   dd  20  400.0  BBB
11    l  11.0 -1200.0  Dec   dd  20  400.0  BBB
12  NaN   NaN     NaN  NaN  NaN  30    NaN  CCC
13  NaN   NaN     NaN  NaN  NaN  40    NaN  DDD

The .isnull() method converts a seried inot a BOOLEAN! A TRUE value means the entry is MISSING, while a FALSE corresponds to the value being present

In [42]:
df.B.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
Name: B, dtype: bool

By applying .isnull() to the ENTIRE DataFrame returns a DATAFRAME of Booleans!

In [43]:
df.isnull()

        A      B      C      D      E      F      G      H
0   False  False  False  False  False  False  False  False
1   False  False  False  False  False  False  False  False
2   False  False  False  False  False  False  False  False
3   False  False  False  False  False  False   True  False
4   False  False  False  False  False  False   True  False
5   False  False  False  False  False  False  False  False
6   False  False  False  False  False  False  False  False
7   False  False  False  False  False  False  False  False
8   False  False  False  False  False  False  False  False
9   False  False  False  False  False  False   True  False
10  False  False  False  False  False  False  False  False
11  False  False  False  False  False  False  False  False
12   True   True   True   True   True  False   True  False
13   True   True   True   True   True  False   True  False

In [45]:
df.isna()

        A      B      C      D      E      F      G      H
0   False  False  False  False  False  False  False  False
1   False  False  False  False  False  False  False  False
2   False  False  False  False  False  False  False  False
3   False  False  False  False  False  False   True  False
4   False  False  False  False  False  False   True  False
5   False  False  False  False  False  False  False  False
6   False  False  False  False  False  False  False  False
7   False  False  False  False  False  False  False  False
8   False  False  False  False  False  False  False  False
9   False  False  False  False  False  False   True  False
10  False  False  False  False  False  False  False  False
11  False  False  False  False  False  False  False  False
12   True   True   True   True   True  False   True  False
13   True   True   True   True   True  False   True  False

Since the result is a DataFrame we can now apply any appropreate summary method to the Boolean DataFrame
such as SUMMING the total number of MISSINGS!

In [47]:
df.isna().sum()

A    2
B    2
C    2
D    2
E    2
F    0
G    5
H    0
dtype: int64

If you want the PROPORTION missing apply the .mean() method instead of .sum()

In [48]:
df.isna().mean()

A    0.142857
B    0.142857
C    0.142857
D    0.142857
E    0.142857
F    0.000000
G    0.357143
H    0.000000
dtype: float64

 The above is the summary per column...but we can also summarize per row!
 The result shown below is the number of MISSINGS within each ROW!!!

In [50]:
df.isna().sum(axis=1)

0     0
1     0
2     0
3     1
4     1
5     0
6     0
7     0
8     0
9     1
10    0
11    0
12    6
13    6
dtype: int64

This is a simple way to identify ROWS with ZERO missing or the ROW is COMPLETE!!!

In [51]:
df.loc[df.isna().sum(axis=1) == 0, :]

    A     B       C    D   E   F      G    H
0   a   0.0  -100.0  Jan  aa  10  100.0  AAA
1   c   2.0  -300.0  Mar  aa  10  100.0  AAA
2   e   4.0  -500.0  May  bb  10  200.0  AAA
5   k  10.0 -1100.0  Nov  dd  10  400.0  AAA
6   b   1.0  -200.0  Feb  aa  20  100.0  BBB
7   d   3.0  -400.0  Apr  bb  20  200.0  BBB
8   f   5.0  -600.0  Jun  bb  20  200.0  BBB
10  j   9.0 -1000.0  Oct  dd  20  400.0  BBB
11  l  11.0 -1200.0  Dec  dd  20  400.0  BBB

This idea of removing ALL missings, or remove any row that has at least 1 missing column...is known as creating the **COMPLETE CASES**
This is what happens behind the scenes in a LOT OF MODELING FUNCTIONS!!!

In [52]:
df.shape

(14, 8)

In [53]:
df.loc[df.isna().sum(axis=1) == 0, :].shape

(9, 8)

There is a stramlined operation for creating the COMPLETE CASES!

In [54]:
df.dropna()

    A     B       C    D   E   F      G    H
0   a   0.0  -100.0  Jan  aa  10  100.0  AAA
1   c   2.0  -300.0  Mar  aa  10  100.0  AAA
2   e   4.0  -500.0  May  bb  10  200.0  AAA
5   k  10.0 -1100.0  Nov  dd  10  400.0  AAA
6   b   1.0  -200.0  Feb  aa  20  100.0  BBB
7   d   3.0  -400.0  Apr  bb  20  200.0  BBB
8   f   5.0  -600.0  Jun  bb  20  200.0  BBB
10  j   9.0 -1000.0  Oct  dd  20  400.0  BBB
11  l  11.0 -1200.0  Dec  dd  20  400.0  BBB