## CMPINF 2100 Week 05
### Essential Exploratory Data Analysis (EDA) Pandas Methods
We have used many different Pandas attributes and methods over the last two weeks. Let's review the most essential ones that you will use when you BEGIN exploring data

In [1]:
import numpy as np
import pandas as pd

## Read data
Let's continue to work with the JOINED data set that we created previously

In [2]:
df = pd.read_csv('joined_data.csv')

In [3]:
df

      A     B       C    D    E   F      G    H
0     a   0.0  -100.0  Jan   aa  10  100.0  AAA
1     c   2.0  -300.0  Mar   aa  10  100.0  AAA
2     e   4.0  -500.0  May   bb  10  200.0  AAA
3     g   6.0  -700.0  Jul   cc  10    NaN  AAA
4     i   8.0  -900.0  Sep   cc  10    NaN  AAA
5     k  10.0 -1100.0  Nov   dd  10  400.0  AAA
6     b   1.0  -200.0  Feb   aa  20  100.0  BBB
7     d   3.0  -400.0  Apr   bb  20  200.0  BBB
8     f   5.0  -600.0  Jun   bb  20  200.0  BBB
9     h   7.0  -800.0  Aug   cc  20    NaN  BBB
10    j   9.0 -1000.0  Oct   dd  20  400.0  BBB
11    l  11.0 -1200.0  Dec   dd  20  400.0  BBB
12  NaN   NaN     NaN  NaN  NaN  30    NaN  CCC
13  NaN   NaN     NaN  NaN  NaN  40    NaN  DDD

this is a small dataset so we can visually look at them and analyze but when there are thousands of data it is impossible
What are the basic actions that we should perform for any data analysis task?
### Exploratory Data Analysis (EDA)

Know the number of columns and rows

In [4]:
df.shape

(14, 8)

Know the names of columns

In [5]:
df.columns

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'], dtype='object')

Know the types of columns

In [6]:
df.dtypes

A     object
B    float64
C    float64
D     object
E     object
F      int64
G    float64
H     object
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       12 non-null     object
 1   B       12 non-null     float64
 2   C       12 non-null     float64
 3   D       12 non-null     object
 4   E       12 non-null     object
 5   F       14 non-null     int64
 6   G       9 non-null      float64
 7   H       14 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 1.0+ KB

In [8]:
df.dtypes.value_counts()

object     4
float64    3
int64      1
Name: count, dtype: int64

Know the cells that miss the value

In [9]:
df.isna().sum()

A    2
B    2
C    2
D    2
E    2
F    0
G    5
H    0
dtype: int64

In [10]:
df.isna().sum()[df.isna().sum() < 1]

F    0
H    0
dtype: int64

In [11]:
df.isna().sum()[df.isna().sum() > 0]

A    2
B    2
C    2
D    2
E    2
G    5
dtype: int64

Know the number of unique values

In [12]:
df.nunique()

A    12
B    12
C    12
D    12
E     4
F     4
G     3
H     4
dtype: int64

.nunique() method does NOT treat MISSINGS as a VALUE, it drops the missing values

In [13]:
df.nunique(dropna=True)

A    12
B    12
C    12
D    12
E     4
F     4
G     3
H     4
dtype: int64

By default dropna is True in nunique method and if you turn it to false it will count the missing value

In [15]:
df.nunique(dropna=False)

A    13
B    13
C    13
D    13
E     5
F     4
G     4
H     4
dtype: int64

It is always important to begin summarizing the columns

In [17]:
df.mean(numeric_only=True)

B      5.500000
C   -650.000000
F     17.857143
G    233.333333
dtype: float64

instead of going for individual mthods form mean, std etc we can have .describe() method

In [18]:
df.describe()

               B            C          F           G
count  12.000000    12.000000  14.000000    9.000000
mean    5.500000  -650.000000  17.857143  233.333333
std     3.605551   360.555128   8.925824  132.287566
min     0.000000 -1200.000000  10.000000  100.000000
25%     2.750000  -925.000000  10.000000  100.000000
50%     5.500000  -650.000000  20.000000  200.000000
75%     8.250000  -375.000000  20.000000  400.000000
max    11.000000  -100.000000  40.000000  400.000000

by default .describe select only numeric columns we can change that with include

In [19]:
df.describe(include='object')

         A    D   E    H
count   12   12  12   14
unique  12   12   4    4
top      a  Jan  aa  AAA
freq     1    1   3    6

In [21]:
df.describe(include='all') #not recommended

          A          B            C    D    E          F           G    H
count    12  12.000000    12.000000   12   12  14.000000    9.000000   14
unique   12        NaN          NaN   12    4        NaN         NaN    4
top       a        NaN          NaN  Jan   aa        NaN         NaN  AAA
freq      1        NaN          NaN    1    3        NaN         NaN    6
mean    NaN   5.500000  -650.000000  NaN  NaN  17.857143  233.333333  NaN
std     NaN   3.605551   360.555128  NaN  NaN   8.925824  132.287566  NaN
min     NaN   0.000000 -1200.000000  NaN  NaN  10.000000  100.000000  NaN
25%     NaN   2.750000  -925.000000  NaN  NaN  10.000000  100.000000  NaN
50%     NaN   5.500000  -650.000000  NaN  NaN  20.000000  200.000000  NaN
75%     NaN   8.250000  -375.000000  NaN  NaN  20.000000  400.000000  NaN
max     NaN  11.000000  -100.000000  NaN  NaN  40.000000  400.000000  NaN

The next step is to begin counting the categorical/string columns!

In [22]:
df.A.value_counts()

A
a    1
c    1
e    1
g    1
i    1
k    1
b    1
d    1
f    1
h    1
j    1
l    1
Name: count, dtype: int64

value_counts by default skip the missing values dropna=False will include them

In [23]:
df.A.value_counts(dropna=False)

A
NaN    2
a      1
c      1
e      1
g      1
i      1
k      1
b      1
d      1
f      1
h      1
j      1
l      1
Name: count, dtype: int64

In [24]:
df.E.value_counts(dropna=False)

E
aa     3
bb     3
cc     3
dd     3
NaN    2
Name: count, dtype: int64

we can know the proportion of these values using normalize=True

In [25]:
df.E.value_counts(dropna=False, normalize=True)

E
aa     0.214286
bb     0.214286
cc     0.214286
dd     0.214286
NaN    0.142857
Name: proportion, dtype: float64

always show the row count before showing proportion

In [26]:
df.H.value_counts(dropna=False)

H
AAA    6
BBB    6
CCC    1
DDD    1
Name: count, dtype: int64

In [27]:
df.H.value_counts(dropna=False, normalize=True)

H
AAA    0.428571
BBB    0.428571
CCC    0.071429
DDD    0.071429
Name: proportion, dtype: float64

In [28]:
df.F.value_counts()

F
10    6
20    6
30    1
40    1
Name: count, dtype: int64

In [29]:
df.F.value_counts(dropna=False, normalize=True)

F
10    0.428571
20    0.428571
30    0.071429
40    0.071429
Name: proportion, dtype: float64

## Realistic Example
Let's follow the same steps to get the same type of BASIC information on a real data set!!!

In [30]:
import seaborn as sns

In [31]:
titanic = sns.load_dataset('titanic')

In [32]:
titanic.shape

(891, 15)

In [34]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [35]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [36]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [38]:
titanic.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [40]:
titanic.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
embarked         object
class          category
who              object
adult_male         bool
deck           category
embark_town      object
alive            object
alone              bool
dtype: object

In [41]:
titanic.dtypes.value_counts()

object      5
int64       4
float64     2
bool        2
category    1
category    1
Name: count, dtype: int64

In [43]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [44]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [45]:
titanic.isna().sum()[titanic.isna().sum() > 0]

age            177
embarked         2
deck           688
embark_town      2
dtype: int64

In [46]:
titanic.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [47]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [48]:
titanic.survived.value_counts()

survived
0    549
1    342
Name: count, dtype: int64

In [49]:
titanic.survived.value_counts(dropna=False, normalize=True)

survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [51]:
titanic.describe(include='object')

         sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

In [52]:
titanic.alive.value_counts()

alive
no     549
yes    342
Name: count, dtype: int64

In [53]:
titanic.describe(include='category')

        class deck
count     891  203
unique      3    7
top     Third    C
freq      491   59

In [54]:
titanic.describe(include='boolean')

       adult_male alone
count         891   891
unique          2     2
top          True  True
freq          537   537

In [55]:
titanic.pclass.value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [56]:
titanic.pclass.value_counts(dropna=False, normalize=True)

pclass
3    0.551066
1    0.242424
2    0.206510
Name: proportion, dtype: float64

In [59]:
titanic['class'].value_counts() #class is a reserved word in python so we can't use .class

class
Third     491
First     216
Second    184
Name: count, dtype: int64

In [62]:
titanic.deck.value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [63]:
titanic.deck.value_counts(dropna=False)

deck
NaN    688
C       59
B       47
D       33
E       32
A       15
F       13
G        4
Name: count, dtype: int64

In [64]:
titanic.deck.value_counts(dropna=False, normalize=True)

deck
NaN    0.772166
C      0.066218
B      0.052750
D      0.037037
E      0.035915
A      0.016835
F      0.014590
G      0.004489
Name: proportion, dtype: float64