## CMPINF 2100 Week 05
### Combine DataFrames - Concatenation
### Import modules

In [29]:
import numpy as np
import pandas as pd

## Read Data
Read in the Example A CSV file discussed in the previous session

In [30]:
dfa0 = pd.read_csv('Example_A.csv')

In [31]:
dfa0

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

Add a column with constant value of 0

In [32]:
dfa0['attempt']=0

In [33]:
dfa0

    A   B     C    D   E   F  attempt
0   a   0  -100  Jan  aa  10        0
1   b   1  -200  Feb  aa  20        0
2   c   2  -300  Mar  aa  10        0
3   d   3  -400  Apr  bb  20        0
4   e   4  -500  May  bb  10        0
5   f   5  -600  Jun  bb  20        0
6   g   6  -700  Jul  cc  10        0
7   h   7  -800  Aug  cc  20        0
8   i   8  -900  Sep  cc  10        0
9   j   9 -1000  Oct  dd  20        0
10  k  10 -1100  Nov  dd  10        0
11  l  11 -1200  Dec  dd  20        0

Read in th same csv file again

In [34]:
dfa1 = pd.read_csv('Example_A.csv')

In [35]:
dfa1

    A   B     C    D   E   F
0   a   0  -100  Jan  aa  10
1   b   1  -200  Feb  aa  20
2   c   2  -300  Mar  aa  10
3   d   3  -400  Apr  bb  20
4   e   4  -500  May  bb  10
5   f   5  -600  Jun  bb  20
6   g   6  -700  Jul  cc  10
7   h   7  -800  Aug  cc  20
8   i   8  -900  Sep  cc  10
9   j   9 -1000  Oct  dd  20
10  k  10 -1100  Nov  dd  10
11  l  11 -1200  Dec  dd  20

In [36]:
 dfa1['attempt']=1

In [37]:
dfa1

    A   B     C    D   E   F  attempt
0   a   0  -100  Jan  aa  10        1
1   b   1  -200  Feb  aa  20        1
2   c   2  -300  Mar  aa  10        1
3   d   3  -400  Apr  bb  20        1
4   e   4  -500  May  bb  10        1
5   f   5  -600  Jun  bb  20        1
6   g   6  -700  Jul  cc  10        1
7   h   7  -800  Aug  cc  20        1
8   i   8  -900  Sep  cc  10        1
9   j   9 -1000  Oct  dd  20        1
10  k  10 -1100  Nov  dd  10        1
11  l  11 -1200  Dec  dd  20        1

### Vertically concactenate

In [38]:
pd.concat([dfa0, dfa1])

    A   B     C    D   E   F  attempt
0   a   0  -100  Jan  aa  10        0
1   b   1  -200  Feb  aa  20        0
2   c   2  -300  Mar  aa  10        0
3   d   3  -400  Apr  bb  20        0
4   e   4  -500  May  bb  10        0
5   f   5  -600  Jun  bb  20        0
6   g   6  -700  Jul  cc  10        0
7   h   7  -800  Aug  cc  20        0
8   i   8  -900  Sep  cc  10        0
9   j   9 -1000  Oct  dd  20        0
10  k  10 -1100  Nov  dd  10        0
11  l  11 -1200  Dec  dd  20        0
0   a   0  -100  Jan  aa  10        1
1   b   1  -200  Feb  aa  20        1
2   c   2  -300  Mar  aa  10        1
3   d   3  -400  Apr  bb  20        1
4   e   4  -500  May  bb  10        1
5   f   5  -600  Jun  bb  20        1
6   g   6  -700  Jul  cc  10        1
7   h   7  -800  Aug  cc  20        1
8   i   8  -900  Sep  cc  10        1
9   j   9 -1000  Oct  dd  20        1
10  k  10 -1100  Nov  dd  10        1
11  l  11 -1200  Dec  dd  20        1

This works because Both DataFrames have the same column names

In [39]:
dfa0.columns == dfa1.columns

array([ True,  True,  True,  True,  True,  True,  True])

In [40]:
dfA_double = pd.concat([dfa0, dfa1], ignore_index=True, copy=True) #ignoring index  to make the series and taking a deep copy

In [41]:
dfA_double

    A   B     C    D   E   F  attempt
0   a   0  -100  Jan  aa  10        0
1   b   1  -200  Feb  aa  20        0
2   c   2  -300  Mar  aa  10        0
3   d   3  -400  Apr  bb  20        0
4   e   4  -500  May  bb  10        0
5   f   5  -600  Jun  bb  20        0
6   g   6  -700  Jul  cc  10        0
7   h   7  -800  Aug  cc  20        0
8   i   8  -900  Sep  cc  10        0
9   j   9 -1000  Oct  dd  20        0
10  k  10 -1100  Nov  dd  10        0
11  l  11 -1200  Dec  dd  20        0
12  a   0  -100  Jan  aa  10        1
13  b   1  -200  Feb  aa  20        1
14  c   2  -300  Mar  aa  10        1
15  d   3  -400  Apr  bb  20        1
16  e   4  -500  May  bb  10        1
17  f   5  -600  Jun  bb  20        1
18  g   6  -700  Jul  cc  10        1
19  h   7  -800  Aug  cc  20        1
20  i   8  -900  Sep  cc  10        1
21  j   9 -1000  Oct  dd  20        1
22  k  10 -1100  Nov  dd  10        1
23  l  11 -1200  Dec  dd  20        1

## Horizontal concatenation
Bindin columns togetehr
The defult axis is 0 - means it will be virtically combine by defalt
To do a horizontal concatenation we go for axis=1

In [42]:
pd.concat([dfa0, dfa1], axis=1)

    A   B     C    D   E   F  attempt  A   B     C    D   E   F  attempt
0   a   0  -100  Jan  aa  10        0  a   0  -100  Jan  aa  10        1
1   b   1  -200  Feb  aa  20        0  b   1  -200  Feb  aa  20        1
2   c   2  -300  Mar  aa  10        0  c   2  -300  Mar  aa  10        1
3   d   3  -400  Apr  bb  20        0  d   3  -400  Apr  bb  20        1
4   e   4  -500  May  bb  10        0  e   4  -500  May  bb  10        1
5   f   5  -600  Jun  bb  20        0  f   5  -600  Jun  bb  20        1
6   g   6  -700  Jul  cc  10        0  g   6  -700  Jul  cc  10        1
7   h   7  -800  Aug  cc  20        0  h   7  -800  Aug  cc  20        1
8   i   8  -900  Sep  cc  10        0  i   8  -900  Sep  cc  10        1
9   j   9 -1000  Oct  dd  20        0  j   9 -1000  Oct  dd  20        1
10  k  10 -1100  Nov  dd  10        0  k  10 -1100  Nov  dd  10        1
11  l  11 -1200  Dec  dd  20        0  l  11 -1200  Dec  dd  20        1

columns repeat
Column names are nolonger unique
Be careful about horizontal combination
Why would we ever horizontally combine?

In [43]:
dfA_left = dfa0.loc[:, dfa0.columns[:3]].copy()

In [44]:
dfA_left

    A   B     C
0   a   0  -100
1   b   1  -200
2   c   2  -300
3   d   3  -400
4   e   4  -500
5   f   5  -600
6   g   6  -700
7   h   7  -800
8   i   8  -900
9   j   9 -1000
10  k  10 -1100
11  l  11 -1200

In [45]:
dfA_right = dfa0.loc[:, dfa0.columns[-2:]].copy()

In [46]:
dfA_right

     F  attempt
0   10        0
1   20        0
2   10        0
3   20        0
4   10        0
5   20        0
6   10        0
7   20        0
8   10        0
9   20        0
10  10        0
11  20        0

In [47]:
 dfA_right.shape

(12, 2)

The point of horizontally combining is to bring together DIFFERENT columns that have the same number of rows

In [48]:
pd.concat([dfA_left, dfA_right], axis=1)

    A   B     C   F  attempt
0   a   0  -100  10        0
1   b   1  -200  20        0
2   c   2  -300  10        0
3   d   3  -400  20        0
4   e   4  -500  10        0
5   f   5  -600  20        0
6   g   6  -700  10        0
7   h   7  -800  20        0
8   i   8  -900  10        0
9   j   9 -1000  20        0
10  k  10 -1100  10        0
11  l  11 -1200  20        0

BUT be carefule if you remove the index with horizontal concactenation...you will REMOVE the column names!!!

In [50]:
pd.concat([dfA_left, dfA_right], axis=1, ignore_index=True)

    0   1     2   3  4
0   a   0  -100  10  0
1   b   1  -200  20  0
2   c   2  -300  10  0
3   d   3  -400  20  0
4   e   4  -500  10  0
5   f   5  -600  20  0
6   g   6  -700  10  0
7   h   7  -800  20  0
8   i   8  -900  10  0
9   j   9 -1000  20  0
10  k  10 -1100  10  0
11  l  11 -1200  20  0