## CMPINF 2100 Week 10

### FIt a linear model

Fit a linear model consisting of a SINGLE continuous INPUT that is LINEARLY RELATED to the TREND or MEAN OUTPUT

This is your classic "best fit line"

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns

We need one more module to FIT the linear model

We will use `statsmodels` to FIT the linear models for regression. Later we will use sklearn form fitting the linear model. But let's stat with the `statsmodels` FORMULA API!!!

In [2]:
import statsmodels.formula.api as smf

In [3]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
pd         module    <module 'pandas' from '/o<...>ages/pandas/__init__.py'>
plt        module    <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
smf        module    <module 'statsmodels.form<...>tsmodels/formula/api.py'>
sns        module    <module 'seaborn' from '/<...>ges/seaborn/__init__.py'>

## Read data
We will use the very simple linear relationship example that we created previously

In [4]:
df = pd.read_csv('week_10_linear_data.csv')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   x               9 non-null      float64
 1   trend           9 non-null      float64
 2   y               9 non-null      float64
 3   true_intercept  9 non-null      float64
 4   true_slope      9 non-null      float64
 5   true_sigma      9 non-null      float64
dtypes: float64(6)
memory usage: 560.0 bytes

We will fit a LINEAR MODEL between the INPUT `x` and OUTPUT `y` assuming a LINEAR RELATIONSHIP between the TREND and the INPUT

## Fitting

The statsmodels function for fitting LINEAR MODELS for regression is `smf.ols()` (ols = ordinary least squares).

The `smf.ols()` function works slightly differently than how sklearn works. The object is INITIALIZED with a DATA SET!!!

You then FIT the object with the `.fit()` method BUT the data has already been provided!!

The model we want to FIT is specified via the `formula` argument to `smf.ols()`.

The FORMULA is a STRING!!!

`'<OUTPUT> ~ <INPUT>'`

By default the FORMULA assumes an INTERCEPT **MUST BE ESTIMATED**!!!

The resulting FITTED object will include all COEFFICIENT ESTIMATES, STANDARD ERRORS, CONFIDENCE INTERVALS, and most PERFORMANCE metrics.

In [7]:
lm_fit = smf.ols(formula='y ~ x' , data=df ).fit()

In [8]:
type(lm_fit)

statsmodels.regression.linear_model.RegressionResultsWrapper

In [9]:
dir(lm_fit)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abat_diagonal',
 '_cache',
 '_data_attr',
 '_data_in_cache',
 '_get_robustcov_results',
 '_get_wald_nonlinear',
 '_is_nested',
 '_transform_predict_exog',
 '_use_t',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_prediction',
 'get_robustcov_results',
 'info_criteria',
 'initialize',
 'k_constant',
 'llf',
 'load',
 'model',
 'mse_model',
 'mse_resid',
 'mse_total',
 'nobs',
 'normalized_cov_params',
 'outlier_test',
 'params',
 'predict',
 'pvalues',
 'remove_data',
 'resid',
 'resid_pearson',
 'rsquared',
 'rsquared_adj',
 'save',
 'scale',
 'ssr',
 'summary',
 'summary2',
 't_test',
 't_test_pairwise',
 'tvalues',
 'uncentered_tss',
 'use_t',
 'wald_test',
 'wald_test_terms',
 'wresid']

The `.summary()` is a useful METHOD for SUMMARIZING the linear model FIT!!!

In [10]:
lm_fit.summary()

/opt/anaconda3/envs/cmpinf2100/lib/python3.8/site-packages/scipy/stats/_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.918
Model:                            OLS   Adj. R-squared:                  0.907
Method:                 Least Squares   F-statistic:                     78.82
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           4.66e-05
Time:                        15:30:18   Log-Likelihood:                -12.580
No. Observations:                   9   AIC:                             29.16
Df Residuals:                       7   BIC:                             29.55
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.4765      0.370     -1.288      0.239      -1.352       0.398
x             -1.6964      0.191     -8.878      0.000      -2.148      -1.245
==============================================================================
Omnibus:                        0.301   Durbin-Watson:                   2.978
Prob(Omnibus):                  0.860   Jarque-Bera (JB):                0.330
Skew:                          -0.315   Prob(JB):                        0.848
Kurtosis:                       2.306   Cond. No.                         1.94
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

print the summary

In [12]:
print(lm_fit.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.918
Model:                            OLS   Adj. R-squared:                  0.907
Method:                 Least Squares   F-statistic:                     78.82
Date:                Thu, 04 Jun 2026   Prob (F-statistic):           4.66e-05
Time:                        15:31:21   Log-Likelihood:                -12.580
No. Observations:                   9   AIC:                             29.16
Df Residuals:                       7   BIC:                             29.55
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -0.4765      0.370     -1.288      0.239      -1.352       0.398
x             -1.6964      0.191     -8.878      0.000      -2.148      -1.245
==============================================================================
Omnibus:                        0.301   Durbin-Watson:                   2.978
Prob(Omnibus):                  0.860   Jarque-Bera (JB):                0.330
Skew:                          -0.315   Prob(JB):                        0.848
Kurtosis:                       2.306   Cond. No.                         1.94
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

/opt/anaconda3/envs/cmpinf2100/lib/python3.8/site-packages/scipy/stats/_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

As a reminder, the FORMULA `'y ~ x'` stands for:

$$\mu = \beta_0 + \beta_1 \times x $$

The `.params` attribute stores the COEFFICIENT ESTIMATES!!! These are teh estimates that MINIMIZE the sum of squared errors!!

In [13]:
lm_fit.params

Intercept   -0.476523
x           -1.696400
dtype: float64

The standard error on the estimate is contained in the `.bse` attribute

In [14]:
lm_fit.bse

Intercept    0.370031
x            0.191083
dtype: float64

Essentially we can use the $\pm1$ and $\pm2$ standard error intervals to know how TURSTWORTHY the estimate is !!!

The most common standard error interval is the $\pm2$ standard error interval because that is approximately equal to the 95% CONFIDENCE INTERVAL!!!

In [15]:
lm_fit.params - 2 * lm_fit.bse

Intercept   -1.216585
x           -2.078566
dtype: float64

In [17]:
lm_fit.params + 2 * lm_fit.bse

Intercept    0.263538
x           -1.314234
dtype: float64

The actual 95% confidence interval is a slightly more difficult formula. But when the sample size is high our approximation using the Gaussian becomes really good. If you want the EXACT 95% confidence interval then you can extract it using the `.conf_int()`

In [18]:
lm_fit.conf_int()

                  0        1
Intercept -1.351507  0.39846
x         -2.148239 -1.24456

Let's change the column names to the CONFIDENCE INTERVAL LOWER BOUND and the CONFIDENCE INTERVAL UPPER BOUND

In [23]:
lm_fit.conf_int().\
rename(columns={0: 'ci_lwr', 1: 'ci_upr'})

             ci_lwr   ci_upr
Intercept -1.351507  0.39846
x         -2.148239 -1.24456